// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260602173858_AddContactMessageAndReviewSubmissionSuupport")]
    partial class AddContactMessageAndReviewSubmissionSuupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("API.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("API.Entities.ClientReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsApproved");

                    b.HasIndex("UserId");

                    b.HasIndex("IsFeatured", "DisplayOrder");

                    b.ToTable("ClientReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Client review profile",
                            ClientName = "Lerato M.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "assets/gallery/makeup/3.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Cape Town, GP",
                            Rating = 5,
                            ReviewText = "Absolutely love my nails! The attention to detail and overall experience was beyond amazing."
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Client review profile",
                            ClientName = "Asanda R.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            ImageUrl = "assets/gallery/makeup/8.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Joburg, SL",
                            Rating = 5,
                            ReviewText = "The best pedicure I have ever had. So relaxing and my feet have never looked better!"
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Client review profile",
                            ClientName = "Nontutuzelo L.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            ImageUrl = "assets/gallery/makeup/12.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Bloemfontein, CBD",
                            Rating = 5,
                            ReviewText = "My brows and lashes have never looked this good. I feel so confident every single day."
                        },
                        new
                        {
                            Id = 4,
                            AltText = "Client review profile",
                            ClientName = "Thando K.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            ImageUrl = "assets/gallery/makeup/15.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Kimberley, NC",
                            Rating = 5,
                            ReviewText = "The makeup finish was soft, clean, and exactly what I wanted for my event."
                        },
                        new
                        {
                            Id = 5,
                            AltText = "Client review profile",
                            ClientName = "Anele D.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            ImageUrl = "assets/gallery/makeup/18.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Durban, KZN",
                            Rating = 5,
                            ReviewText = "My manicure lasted beautifully and the whole appointment felt calm and professional."
                        },
                        new
                        {
                            Id = 6,
                            AltText = "Client review profile",
                            ClientName = "Mpho S.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            ImageUrl = "assets/gallery/makeup/20.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Pretoria, GP",
                            Rating = 5,
                            ReviewText = "The lash set was neat, comfortable, and gave me the exact natural glam I asked for."
                        },
                        new
                        {
                            Id = 7,
                            AltText = "Client review profile",
                            ClientName = "Zanele B.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            ImageUrl = "assets/gallery/makeup/5.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Gqeberha, EC",
                            Rating = 5,
                            ReviewText = "Beautiful service from start to finish. I left feeling pampered and confident."
                        },
                        new
                        {
                            Id = 8,
                            AltText = "Client review profile",
                            ClientName = "Naledi P.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            ImageUrl = "assets/gallery/makeup/9.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Polokwane, LP",
                            Rating = 5,
                            ReviewText = "The team listened carefully and delivered a clean, elegant look that suited me perfectly."
                        },
                        new
                        {
                            Id = 9,
                            AltText = "Client review profile",
                            ClientName = "Refilwe T.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            ImageUrl = "assets/gallery/makeup/11.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Rustenburg, NW",
                            Rating = 5,
                            ReviewText = "I loved the attention to detail. My nails looked polished, feminine, and flawless."
                        },
                        new
                        {
                            Id = 10,
                            AltText = "Client review profile",
                            ClientName = "Boitumelo N.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            ImageUrl = "assets/gallery/makeup/14.svg",
                            IsApproved = true,
                            IsFeatured = true,
                            Location = "Bloemfontein, FS",
                            Rating = 5,
                            ReviewText = "The pedicure was relaxing and my feet looked fresh for weeks. I would definitely return."
                        });
                });

            modelBuilder.Entity("API.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Interest")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MessageStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageStatus");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("UserId");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("API.Entities.HomeHeroImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImageUrl")
                        .IsUnique();

                    b.HasIndex("Category", "DisplayOrder");

                    b.ToTable("HomeHeroImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Makeup beauty inspiration 1",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "assets/gallery/makeup/1.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Makeup beauty inspiration 2",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            ImageUrl = "assets/gallery/makeup/2.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Makeup beauty inspiration 3",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            ImageUrl = "assets/gallery/makeup/3.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            AltText = "Makeup beauty inspiration 4",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            ImageUrl = "assets/gallery/makeup/4.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            AltText = "Makeup beauty inspiration 5",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            ImageUrl = "assets/gallery/makeup/5.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            AltText = "Makeup beauty inspiration 6",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            ImageUrl = "assets/gallery/makeup/6.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            AltText = "Makeup beauty inspiration 7",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            ImageUrl = "assets/gallery/makeup/7.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            AltText = "Makeup beauty inspiration 8",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            ImageUrl = "assets/gallery/makeup/8.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            AltText = "Makeup beauty inspiration 9",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            ImageUrl = "assets/gallery/makeup/9.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            AltText = "Makeup beauty inspiration 10",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            ImageUrl = "assets/gallery/makeup/10.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            AltText = "Makeup beauty inspiration 11",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 11,
                            ImageUrl = "assets/gallery/makeup/11.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            AltText = "Makeup beauty inspiration 12",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 12,
                            ImageUrl = "assets/gallery/makeup/12.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            AltText = "Makeup beauty inspiration 13",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 13,
                            ImageUrl = "assets/gallery/makeup/13.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            AltText = "Makeup beauty inspiration 14",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 14,
                            ImageUrl = "assets/gallery/makeup/14.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            AltText = "Makeup beauty inspiration 15",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 15,
                            ImageUrl = "assets/gallery/makeup/15.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            AltText = "Makeup beauty inspiration 16",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 16,
                            ImageUrl = "assets/gallery/makeup/16.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 17,
                            AltText = "Makeup beauty inspiration 17",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 17,
                            ImageUrl = "assets/gallery/makeup/17.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 18,
                            AltText = "Makeup beauty inspiration 18",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 18,
                            ImageUrl = "assets/gallery/makeup/18.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 19,
                            AltText = "Makeup beauty inspiration 19",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 19,
                            ImageUrl = "assets/gallery/makeup/19.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 20,
                            AltText = "Makeup beauty inspiration 20",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 20,
                            ImageUrl = "assets/gallery/makeup/20.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 21,
                            AltText = "Makeup beauty inspiration 21",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 21,
                            ImageUrl = "assets/gallery/makeup/21.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 22,
                            AltText = "Makeup beauty inspiration 22",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 22,
                            ImageUrl = "assets/gallery/makeup/22.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 23,
                            AltText = "Makeup beauty inspiration 23",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 23,
                            ImageUrl = "assets/gallery/makeup/23.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 24,
                            AltText = "Makeup beauty inspiration 24",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 24,
                            ImageUrl = "assets/gallery/makeup/24.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 25,
                            AltText = "Makeup beauty inspiration 25",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 25,
                            ImageUrl = "assets/gallery/makeup/25.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 26,
                            AltText = "Makeup beauty inspiration 26",
                            Category = "makeup",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 26,
                            ImageUrl = "assets/gallery/makeup/26.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 27,
                            AltText = "Eyelash beauty inspiration 1",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "assets/gallery/lashes/1.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 28,
                            AltText = "Eyelash beauty inspiration 2",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            ImageUrl = "assets/gallery/lashes/2.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 29,
                            AltText = "Eyelash beauty inspiration 3",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            ImageUrl = "assets/gallery/lashes/3.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 30,
                            AltText = "Eyelash beauty inspiration 4",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            ImageUrl = "assets/gallery/lashes/4.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 31,
                            AltText = "Eyelash beauty inspiration 5",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            ImageUrl = "assets/gallery/lashes/5.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 32,
                            AltText = "Eyelash beauty inspiration 6",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            ImageUrl = "assets/gallery/lashes/6.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 33,
                            AltText = "Eyelash beauty inspiration 7",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            ImageUrl = "assets/gallery/lashes/7.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 34,
                            AltText = "Eyelash beauty inspiration 8",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            ImageUrl = "assets/gallery/lashes/8.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 35,
                            AltText = "Eyelash beauty inspiration 9",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            ImageUrl = "assets/gallery/lashes/9.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 36,
                            AltText = "Eyelash beauty inspiration 10",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            ImageUrl = "assets/gallery/lashes/10.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 37,
                            AltText = "Eyelash beauty inspiration 11",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 11,
                            ImageUrl = "assets/gallery/lashes/11.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 38,
                            AltText = "Eyelash beauty inspiration 12",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 12,
                            ImageUrl = "assets/gallery/lashes/12.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 39,
                            AltText = "Eyelash beauty inspiration 13",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 13,
                            ImageUrl = "assets/gallery/lashes/13.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 40,
                            AltText = "Eyelash beauty inspiration 14",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 14,
                            ImageUrl = "assets/gallery/lashes/14.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 41,
                            AltText = "Eyelash beauty inspiration 15",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 15,
                            ImageUrl = "assets/gallery/lashes/15.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 42,
                            AltText = "Eyelash beauty inspiration 16",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 16,
                            ImageUrl = "assets/gallery/lashes/16.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 43,
                            AltText = "Eyelash beauty inspiration 17",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 17,
                            ImageUrl = "assets/gallery/lashes/17.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 44,
                            AltText = "Eyelash beauty inspiration 18",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 18,
                            ImageUrl = "assets/gallery/lashes/18.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 45,
                            AltText = "Eyelash beauty inspiration 19",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 19,
                            ImageUrl = "assets/gallery/lashes/19.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 46,
                            AltText = "Eyelash beauty inspiration 20",
                            Category = "lashes",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 20,
                            ImageUrl = "assets/gallery/lashes/20.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 47,
                            AltText = "Pedicure beauty inspiration 1",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "assets/gallery/pedicure/1.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 48,
                            AltText = "Pedicure beauty inspiration 2",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            ImageUrl = "assets/gallery/pedicure/2.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 49,
                            AltText = "Pedicure beauty inspiration 3",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            ImageUrl = "assets/gallery/pedicure/3.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 50,
                            AltText = "Pedicure beauty inspiration 4",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            ImageUrl = "assets/gallery/pedicure/4.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 51,
                            AltText = "Pedicure beauty inspiration 5",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            ImageUrl = "assets/gallery/pedicure/5.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 52,
                            AltText = "Pedicure beauty inspiration 6",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            ImageUrl = "assets/gallery/pedicure/6.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 53,
                            AltText = "Pedicure beauty inspiration 7",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            ImageUrl = "assets/gallery/pedicure/7.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 54,
                            AltText = "Pedicure beauty inspiration 8",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            ImageUrl = "assets/gallery/pedicure/8.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 55,
                            AltText = "Pedicure beauty inspiration 9",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            ImageUrl = "assets/gallery/pedicure/9.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 56,
                            AltText = "Pedicure beauty inspiration 10",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            ImageUrl = "assets/gallery/pedicure/10.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 57,
                            AltText = "Pedicure beauty inspiration 11",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 11,
                            ImageUrl = "assets/gallery/pedicure/11.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 58,
                            AltText = "Pedicure beauty inspiration 12",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 12,
                            ImageUrl = "assets/gallery/pedicure/12.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 59,
                            AltText = "Pedicure beauty inspiration 13",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 13,
                            ImageUrl = "assets/gallery/pedicure/13.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 60,
                            AltText = "Pedicure beauty inspiration 14",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 14,
                            ImageUrl = "assets/gallery/pedicure/14.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 61,
                            AltText = "Pedicure beauty inspiration 15",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 15,
                            ImageUrl = "assets/gallery/pedicure/15.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 62,
                            AltText = "Pedicure beauty inspiration 16",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 16,
                            ImageUrl = "assets/gallery/pedicure/16.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 63,
                            AltText = "Pedicure beauty inspiration 17",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 17,
                            ImageUrl = "assets/gallery/pedicure/17.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 64,
                            AltText = "Pedicure beauty inspiration 18",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 18,
                            ImageUrl = "assets/gallery/pedicure/18.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 65,
                            AltText = "Pedicure beauty inspiration 19",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 19,
                            ImageUrl = "assets/gallery/pedicure/19.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 66,
                            AltText = "Pedicure beauty inspiration 20",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 20,
                            ImageUrl = "assets/gallery/pedicure/20.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 67,
                            AltText = "Pedicure beauty inspiration 21",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 21,
                            ImageUrl = "assets/gallery/pedicure/21.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 68,
                            AltText = "Pedicure beauty inspiration 22",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 22,
                            ImageUrl = "assets/gallery/pedicure/22.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 69,
                            AltText = "Pedicure beauty inspiration 23",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 23,
                            ImageUrl = "assets/gallery/pedicure/23.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 70,
                            AltText = "Pedicure beauty inspiration 24",
                            Category = "pedicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 24,
                            ImageUrl = "assets/gallery/pedicure/24.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 71,
                            AltText = "Manicure nail design inspiration 1",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            ImageUrl = "assets/gallery/manicure/1.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 72,
                            AltText = "Manicure nail design inspiration 2",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            ImageUrl = "assets/gallery/manicure/2.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 73,
                            AltText = "Manicure nail design inspiration 3",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            ImageUrl = "assets/gallery/manicure/3.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 74,
                            AltText = "Manicure nail design inspiration 4",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            ImageUrl = "assets/gallery/manicure/4.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 75,
                            AltText = "Manicure nail design inspiration 5",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            ImageUrl = "assets/gallery/manicure/5.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 76,
                            AltText = "Manicure nail design inspiration 6",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            ImageUrl = "assets/gallery/manicure/6.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 77,
                            AltText = "Manicure nail design inspiration 7",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            ImageUrl = "assets/gallery/manicure/7.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 78,
                            AltText = "Manicure nail design inspiration 8",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            ImageUrl = "assets/gallery/manicure/8.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 79,
                            AltText = "Manicure nail design inspiration 9",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            ImageUrl = "assets/gallery/manicure/9.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 80,
                            AltText = "Manicure nail design inspiration 10",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            ImageUrl = "assets/gallery/manicure/10.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 81,
                            AltText = "Manicure nail design inspiration 11",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 11,
                            ImageUrl = "assets/gallery/manicure/11.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 82,
                            AltText = "Manicure nail design inspiration 12",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 12,
                            ImageUrl = "assets/gallery/manicure/12.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 83,
                            AltText = "Manicure nail design inspiration 13",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 13,
                            ImageUrl = "assets/gallery/manicure/13.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 84,
                            AltText = "Manicure nail design inspiration 14",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 14,
                            ImageUrl = "assets/gallery/manicure/14.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 85,
                            AltText = "Manicure nail design inspiration 15",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 15,
                            ImageUrl = "assets/gallery/manicure/15.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 86,
                            AltText = "Manicure nail design inspiration 16",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 16,
                            ImageUrl = "assets/gallery/manicure/16.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 87,
                            AltText = "Manicure nail design inspiration 17",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 17,
                            ImageUrl = "assets/gallery/manicure/17.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 88,
                            AltText = "Manicure nail design inspiration 18",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 18,
                            ImageUrl = "assets/gallery/manicure/18.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 89,
                            AltText = "Manicure nail design inspiration 19",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 19,
                            ImageUrl = "assets/gallery/manicure/19.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 90,
                            AltText = "Manicure nail design inspiration 20",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 20,
                            ImageUrl = "assets/gallery/manicure/20.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 91,
                            AltText = "Manicure nail design inspiration 21",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 21,
                            ImageUrl = "assets/gallery/manicure/21.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 92,
                            AltText = "Manicure nail design inspiration 22",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 22,
                            ImageUrl = "assets/gallery/manicure/22.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 93,
                            AltText = "Manicure nail design inspiration 23",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 23,
                            ImageUrl = "assets/gallery/manicure/23.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 94,
                            AltText = "Manicure nail design inspiration 24",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 24,
                            ImageUrl = "assets/gallery/manicure/24.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 95,
                            AltText = "Manicure nail design inspiration 25",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 25,
                            ImageUrl = "assets/gallery/manicure/25.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 96,
                            AltText = "Manicure nail design inspiration 26",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 26,
                            ImageUrl = "assets/gallery/manicure/26.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 97,
                            AltText = "Manicure nail design inspiration 27",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 27,
                            ImageUrl = "assets/gallery/manicure/27.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 98,
                            AltText = "Manicure nail design inspiration 28",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 28,
                            ImageUrl = "assets/gallery/manicure/28.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 99,
                            AltText = "Manicure nail design inspiration 29",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 29,
                            ImageUrl = "assets/gallery/manicure/29.svg",
                            IsActive = true
                        },
                        new
                        {
                            Id = 100,
                            AltText = "Manicure nail design inspiration 30",
                            Category = "manicure",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 30,
                            ImageUrl = "assets/gallery/manicure/30.svg",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("API.Entities.HomePageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonLink")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ButtonText")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EyebrowText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleLineOne")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleLineOneHighlight")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleLineTwo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleLineTwoHighlight")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SectionKey")
                        .IsUnique();

                    b.ToTable("HomePageContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonLink = "/services",
                            ButtonText = "BOOK APPOINTMENT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Expert nails and makeup services tailored for your unique glow. Look your best, feel your best.",
                            IsActive = true,
                            SectionKey = "hero",
                            TitleLineOne = "Enhance Your Beauty",
                            TitleLineOneHighlight = "Beauty",
                            TitleLineTwo = "Elevate Your Confidence",
                            TitleLineTwoHighlight = "Confidence"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "At MO Beauty, we believe that self-care is more than a routine, it’s a form of self-love. Our expert team is dedicated to enhancing your natural beauty with precision, passion, and care.",
                            EyebrowText = "ABOUT US",
                            IsActive = true,
                            SectionKey = "about",
                            TitleLineOne = "Where Beauty Meets Confidence",
                            TitleLineOneHighlight = "Beauty"
                        });
                });

            modelBuilder.Entity("API.Entities.PasswordResetCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityResetToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetCodes");
                });

            modelBuilder.Entity("API.Entities.SalonService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("IconAltText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeaturedOnHome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("SalonServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Manicure nail design",
                            BasePrice = 250m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Polished to perfection. Every detail.",
                            DisplayOrder = 1,
                            DurationMinutes = 45,
                            IconAltText = "Nail polish icon",
                            IconUrl = "assets/home/nailpolishicon.svg",
                            ImageUrl = "assets/home/nailcardcollage.svg",
                            IsActive = true,
                            IsFeaturedOnHome = true,
                            Name = "MANICURE",
                            Slug = "manicure"
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Makeup service",
                            BasePrice = 550m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flawless looks for every occasion.",
                            DisplayOrder = 2,
                            DurationMinutes = 60,
                            IconAltText = "Makeup brush icon",
                            IconUrl = "assets/home/makeupbrushicon.svg",
                            ImageUrl = "assets/home/makeupcardcollage.svg",
                            IsActive = true,
                            IsFeaturedOnHome = true,
                            Name = "MAKEUP",
                            Slug = "makeup"
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Pedicure service",
                            BasePrice = 300m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Relaxing care for beautiful feet.",
                            DisplayOrder = 3,
                            DurationMinutes = 60,
                            IconAltText = "Bare foot print icon",
                            IconUrl = "assets/home/footprinticon.svg",
                            ImageUrl = "assets/home/pedicurecardcollage.svg",
                            IsActive = true,
                            IsFeaturedOnHome = true,
                            Name = "PEDICURE",
                            Slug = "pedicure"
                        },
                        new
                        {
                            Id = 4,
                            AltText = "Brows and lashes service",
                            BasePrice = 280m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Frame your beauty. Enhance your look.",
                            DisplayOrder = 4,
                            DurationMinutes = 45,
                            IconAltText = "Eyelashes icon",
                            IconUrl = "assets/home/eyelashesicon.svg",
                            ImageUrl = "assets/home/lashescardcollage.svg",
                            IsActive = true,
                            IsFeaturedOnHome = true,
                            Name = "BROWS & LASHES",
                            Slug = "lashes"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Entities.AppUserRole", b =>
                {
                    b.HasOne("API.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.ClientReview", b =>
                {
                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.ContactMessage", b =>
                {
                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.PasswordResetCode", b =>
                {
                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("API.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("API.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("API.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("API.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
